window.team = [
  {
    name: "Олег Мозіль",
    age: "30",
    number: "1",
    position: "Воротар",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_384.png?1758399278",
    goals: "",
    assists: "",
    matches: "",
  },
  {
    name: "Ярослав Проценко",
    age: "24",
    number: "24",
    position: "Воротар",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_482.png?1758864961",
    goals: "",
    assists: "",
    matches: "1",
  },
  {
    name: "Данило Варакута",
    age: "24",
    number: "30",
    position: "Воротар",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_534.png?1776738438",
    goals: "",
    assists: "",
    matches: "29",
  },
  {
    name: "Дмитро Капінус",
    age: "22",
    number: "2",
    position: "Захистник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_381.png?1762228033",
    goals: "",
    assists: "",
    matches: "8",
  },
  {
    name: "Володимир Салюк",
    age: "23",
    number: "13",
    position: "Захистник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_522.png?1776738478",
    goals: "",
    assists: "3",
    matches: "15",
  },
  {
    name: "Євген Павлюк",
    age: "23",
    number: "18",
    position: "Захистник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_576.png?1776738509",
    goals: "2",
    assists: "2",
    matches: "28",
  },
  {
    name: "Олександр Мартинюк",
    age: "24",
    number: "24",
    position: "Захистник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_572.png?1776738592",
    goals: "",
    assists: "",
    matches: "18",
  },
  {
    name: "Ілля Крупський",
    age: "21",
    number: "27",
    position: "Захистник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_556.png?1776738649",
    goals: "",
    assists: "4",
    matches: "29",
  },
  {
    name: "Артем Шабанов",
    age: "34",
    number: "31",
    position: "Захистник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_579.png?1776311695",
    goals: "1",
    assists: "1",
    matches: "27",
  },
  {
    name: "Валерій Дубко",
    age: "25",
    number: "37",
    position: "Захистник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_646.png?1776738544",
    goals: "",
    assists: "",
    matches: "4",
  },
  {
    name: "Ігор Снурніцин",
    age: "26",
    number: "74",
    position: "Захисник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_531.png?1761878151",
    goals: "",
    assists: "",
    matches: "2",
  },
  {
    name: "Іван Калюжний",
    age: "28",
    number: "5",
    position: "Півзахисник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_241.png?1776738726",
    goals: "3",
    assists: "3",
    matches: "27",
  },
  {
    name: "Арі Моура",
    age: "29",
    number: "7",
    position: "Півзахисник",
    nationality: "Бразілія",
    photo: "https://metalist1925.com/players/foto/img_423.png?1776738751",
    goals: "",
    assists: "1",
    matches: "14",
  },
  {
    name: "Себастіан Кастільо",
    age: "20",
    number: "8",
    position: "Півзахисник",
    nationality: "Венесуела",
    photo: "https://metalist1925.com/players/foto/img_642.png?1775761558",
    goals: "",
    assists: "",
    matches: "6",
  },
  {
    name: "В'ячеслав Чурко",
    age: "32",
    number: "11",
    position: "Півзахисник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_512.png?1773711168",
    goals: "1",
    assists: "1",
    matches: "17",
  },
  {
    name: "Рамік Гаджиєв",
    age: "20",
    number: "14",
    position: "Півзахисник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_546.png?1775655147",
    goals: "2",
    assists: "",
    matches: "5",
  },
  {
    name: "Денис Антюх",
    age: "28",
    number: "15",
    position: "Півзахисник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_578.png?1776738926",
    goals: "5",
    assists: "4",
    matches: "27",
  },
  {
    name: "Ніколас Аревало",
    age: "23",
    number: "16",
    position: "Півзахисник",
    nationality: "Колумбія",
    photo: "https://metalist1925.com/players/foto/img_643.png?1776738901",
    goals: "",
    assists: "1",
    matches: "9",
  },
  {
    name: "Ігор Когут",
    age: "30",
    number: "17",
    position: "Півзахисник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_520.png?1776738820",
    goals: "",
    assists: "4",
    matches: "22",
  },
  {
    name: "Ермір Рашиця",
    age: "22",
    number: "19",
    position: "Півзахисник",
    nationality: "Албанія",
    photo: "https://metalist1925.com/players/foto/img_564.png?1776738948",
    goals: "3",
    assists: "2",
    matches: "27",
  },
  {
    name: "Іван Литвиненко",
    age: "25",
    number: "25",
    position: "Півзахисник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_529.png?1776738878",
    goals: "3",
    assists: "1",
    matches: "23",
  },
  {
    name: "Владислав Калітвінцев",
    age: "33",
    number: "45",
    position: "Півзахисник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_513.png?1776311978",
    goals: "1",
    assists: "3",
    matches: "23",
  },
  {
    name: "Кауан Баптістелла",
    age: "18",
    number: "77",
    position: "Півзахисник",
    nationality: "Бразилія",
    photo: "https://metalist1925.com/players/foto/img_648.png?1776738848",
    goals: "1",
    assists: "",
    matches: "8",
  },
  {
    name: "Андрій Король",
    age: "17",
    number: "88",
    position: "Півзахисник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_438.png?1776438498",
    goals: "",
    assists: "",
    matches: "1",
  },
  {
    name: "Матвій Панченко",
    age: "20",
    number: "91",
    position: "Півзахисник",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_411.png?1776438595",
    goals: "",
    assists: "2",
    matches: "5",
  },
  {
    name: "Батон Забергджа",
    age: "25",
    number: "26",
    position: "Нападник",
    nationality: "Косово",
    photo: "https://metalist1925.com/players/foto/img_614.png?1776312055",
    goals: "3",
    assists: "1",
    matches: "21",
  },
  {
    name: "Пітер Ітодо",
    age: "22",
    number: "98",
    position: "Нападник",
    nationality: "Нігерія",
    photo: "https://metalist1925.com/players/foto/img_580.png?1776738970",
    goals: "13",
    assists: "1",
    matches: "26",
  },
  {
    name: "Крістіан Мба",
    age: "26",
    number: "99",
    position: "Нападник",
    nationality: "Бразілія",
    photo: "https://metalist1925.com/players/foto/img_557.png?1776738793",
    goals: "5",
    assists: "",
    matches: "22",
  },
];
window.coaches = [
  {
    name: "Младен Бартулович",
    age: "39",
    position: "Тренерскій штаб",
    coach: "Головний тренер",
    nationality: "Хорватія",
    photo: "https://metalist1925.com/players/foto/img_577.png?1755117221",
  },
  {
    name: "Олександр Чижов",
    age: "39",
    position: "Тренерскій штаб",
    coach: "Помічник головного тренера",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_538.png?1755116118",
  },
  {
    name: "Сергій Долганський",
    age: "51",
    position: "Тренерскій штаб",
    coach: "Тренер воротарів",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_581.png?1755116423",
  },
  {
    name: "Максим Цвіренко",
    age: "27",
    position: "Тренерскій штаб",
    coach: "Асистент тренера",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_161.png?1755116556",
  },
  {
    name: "Євген Шахов",
    age: "35",
    position: "Тренерскій штаб",
    coach: "Асистент тренера",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_590.png?1751656279",
  },
  {
    name: "Валентин Єрмак",
    age: "25",
    position: "Тренерскій штаб",
    coach: "Тренер-аналітик",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_613.png?1755118044",
  },
  {
    name: "Павло Таран",
    age: "37",
    position: "Тренерскій штаб",
    coach: "Тренер-аналітик",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_640.png?1768079073",
  },
  {
    name: "Андрій Шабалін",
    age: "38",
    position: "Тренерскій штаб",
    coach: "Тренер з фізподготовки",
    nationality: "Україна",
    photo: "https://metalist1925.com/players/foto/img_311.png?1755115676",
  },
  {
    name: "Драган Тодорович",
    age: "38",
    position: "Тренерскій штаб",
    coach: "Тренер з фізподготовки",
    nationality: "Хорватія",
    photo: "https://metalist1925.com/players/foto/img_589.png?1755115968",
  },
];

window.managment = [
{
   name: "Богдан Бойко",
   role: "Президент",
   age: "27",
   nationality: "Україна",
   photo: "https://ukrfootball.ua/wp-content/uploads/UPL/Metalist1925/boiko9456.webp",
},
{
   name: "Володимир Носов",
   role: "Голова наглядової ради",
   age: "36",
   nationality: "Україна",
   photo: "https://ukrfootball.ua/wp-content/uploads/UPL/Metalist1925/njsov0.webp",
},
{
   name: "Юрій Коротун",
   role: "Віцепрезидент",
   age: "41",
   nationality: "Україна",
   photo: "https://metalist1925.com/players/foto/img_535.png?1755110054",
},
{
   name: "Антон Іванов",
   role: "Генеральний директор",
   age: "42",
   nationality: "Україна",
   photo: "https://metalist1925.com/players/foto/img_273.png?1734494771",
},
];
  window.matches = [
{
  date: "26.04.26",
  opponent: "ЛНЗ Черкаси",
  time: "15:30",
  place: "Центральний стадіон, Черкаси",
  competition: "УПЛ",
},
{
  date: "03.05.26",
  opponent: "Полісся Житомир",
  time: "15:30",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
},
{
  date: "09.05.26",
  opponent: "Зоря Луганьск",
  time: "18:00",
  place: "Стадіон імені Лобановського, Київ",
  competition: "УПЛ",
},
{
  date: "13.05.26",
  opponent: "Карпати Львів",
  time: "",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
},
{
  date: "16.05.26",
  opponent: "Епіцентр Кам'янець-Подільський",
  time: "",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
},
{
  date: "23.05.26",
  opponent: "Верес Рівне",
  time: "",
  place: "Стадіон Авангард, Рівне",
  competition: "УПЛ",
},
];
window.results = [
{
  date: "26.04.26",
  opponent: "ЛНЗ Черкаси",
  place: "Центральний стадіон, Черкаси",
  competition: "УПЛ",
  score: "1-1",
},
  {
  date: "22.04.26",
  opponent: "ФК Чернигів",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "Кубок України",
  score: "0-0 (5:6 по пенальті)",
},
  {
  date: "18.4.26",
  opponent: "Кудрівка",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
  score: "1-0",
},
{
  date: "15.4.26",
  opponent: "Верес Рівне",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
  score: "4-0",
},  
{
  date: "11.4.26",
  opponent: "Динамо Київ",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
  score: "1-0",
},
{
  date: "4.4.26",
  opponent: "Колос Ковалівка",
  place: "Колос, Ковалівка",
  competition: "УПЛ",
  score: "0-0",
},
{
  date: "19.3.26",
  opponent: "ФК Полтава",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
  score: "2-0",
},
{
  date: "15.3.26",
  opponent: "Шахтар Донецьк",
  place: "Арена Львів, Львів",
  competition: "УПЛ",
  score: "1-0",
},
{
  date: "9.3.26",
  opponent: "Рух Львів",
  place: "Арена Львів, Львів",
  competition: "УПЛ",
  score: "0-3",
},
{
  date: "5.3.26",
  opponent: "Локомотив Київ",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "Кубок України",
  score: "3-0",
},
{
  date: "28.2.26",
  opponent: "Олександрія",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
  score: "1-0",
},
{
  date: "21.2.26",
  opponent: "Кривбас Кривий Ріг",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
  score: "0-0",
},
{
  date: "12.12.25",
  opponent: "Оболонь Київ",
  place: "Оболонь Арена, Київ",
  competition: "УПЛ",
  score: "1-3",
},
{
  date: "30.11.25",
  opponent: "Епіцентр Кам'янець-Подільський",
  place: "Міський стадіон, Тернопіль",
  competition: "УПЛ",
  score: "0-0",
},
{
  date: "22.11.25",
  opponent: "Карпати Львів",
  place: "Стадіон Україна, Львів",
  competition: "УПЛ",
  score: "1-2",
},

{
  date: "8.11.25",
  opponent: "Зоря Луганьск",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
  score: "1-3",
},

{
  date: "3.11.25",
  opponent: "Полісся Житомир",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
  score: "0-0",
},
{
  date: "30.10.25",
  opponent: "Агробізнес Волочиськ",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "Кубок України",
  score: "4-3",
},
{
  date: "25.10.25",
  opponent: "ЛНЗ Черкаси",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
  score: "0-1",
},
{
  date: "28.9.25",
  opponent: "Кудрівка",
  place: "Оболонь Арена, Київ",
  competition: "УПЛ",
  score: "1-1",
},
{
  date: "5.10.25",
  opponent: "Динамо Київ",
  place: "Стадіон імені Лобановського, Київ",
  competition: "УПЛ",
  score: "1-1",
},
{
  date: "28.9.25",
  opponent: "Колос Ковалівка",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
  score: "1-0",
},
{
  date: "24.9.25",
  opponent: "Колос Полонне",
  place: "Полонь, Полонне",
  competition: "Кубок України",
  score: "1-4",
},
{
  date: "21.9.25",
  opponent: "ФК Полтава",
  place: "Стадіон Зірка.Кропивницький",
  competition: "УПЛ",
  score: "0-2",
},
{
  date: "13.9.25",
  opponent: "Шахтар Донецьк",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
  score: "1-1",
},
{
  date: "30.8.25",
  opponent: "Рух Львів",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
  score: "2-0",
},
{
  date: "24.8.25",
  opponent: "Оболонь Київ",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "Кубок України",
  score: "2-0",
},
{
  date: "16.8.25",
  opponent: "Олександрія",
  place: "КСК Ніка, Олександрія",
  competition: "УПЛ",
  score: "1-4",
},

{
  date: "9.8.25",
  opponent: "Кривбас Кривий Ріг",
  place: "Стадіон Гірник, Кривий Ріг",
  competition: "УПЛ",
  score: "2-0",
},
{
  date: "4.8.25",
  opponent: "Оболонь Київ",
  place: "Центральний стадіон Полісся, Житомир",
  competition: "УПЛ",
  score: "0-0",
},
];
