window.team = [
  {
      name: "Ярослав Проценко",
      age: "24",
number: "23",
position: "Воротар",
nationality: "Україна",
photo: "https://fckharkiv.com/uploads/media/other/procenko-d-2026-07-04-t-11-57-59.webp",
goals: "",
assists: "",
matches: "",
  },
  {
      name: "Данило Варакута",
      age: "24",
number: "30",
position: "Воротар",
nationality: "Україна",
photo: "https://fckharkiv.com/uploads/media/other/varakuta-d-2026-07-04-t-11-17-23.webp",
goals: "",
assists: "",
matches: "",
  },
  {
      name: "Микита Гончаров",
      age: "17",
number: "95",
position: "Воротар",
nationality: "Україна",
photo: "https://fckharkiv.com/uploads/media/other/goncarov-d-2026-07-04-t-11-17-23.webp",
goals: "",
assists: "",
matches: "",
  },
  {
      name: "Володимир Салюк",
      age: "24",
number: "13",
position: "Захистник",
nationality: "Україна",
photo: "https://fckharkiv.com/uploads/media/other/saliuk-d-2026-07-04-t-11-17-26.webp",
goals: "",
assists: "",
matches: "",
  },
  {
      name: "Євген Павлюк",
      age: "23",
number: "18",
position: "Захистник",
nationality: "Україна",
photo: "https://fckharkiv.com/uploads/media/other/pavliuk-d-2026-07-04-t-11-17-25.webp",
goals: "",
assists: "",
matches: "",
  },
  {
      name: "Олександр Мартинюк",
      age: "24",
number: "24",
position: "Захистник",
nationality: "Україна",
photo: "https://fckharkiv.com/uploads/media/other/martiniuk-d-2026-07-04-t-11-17-25.webp",
goals: "",
assists: "",
matches: "",
  },
  {
      name: "Ілля Крупський",
      age: "21",
number: "27",
position: "Захистник",
nationality: "Україна",
photo: "https://fckharkiv.com/uploads/media/other/krupskii-d-2026-07-04-t-11-17-25.webp",
goals: "",
assists: "",
matches: "",
  },
  {
      name: "Артем Шабанов",
      age: "34",
number: "31",
position: "Захистник",
nationality: "Україна",
photo: "https://fckharkiv.com/uploads/media/other/sabanov-d-2026-07-04-t-11-17-26.webp",
goals: "",
assists: "",
matches: "",
  },
  {
      name: "Валерій Дубко",
      age: "25",
number: "37",
position: "Захистник",
nationality: "Україна",
photo: "https://fckharkiv.com/uploads/media/other/dubko-d-2026-07-04-t-11-17-23.webp",
goals: "",
assists: "",
matches: "",
  },
  {
      name: "Іван Калюжний",
      age: "28",
number: "5",
position: "Півзахисник",
nationality: "Україна",
photo: "https://fckharkiv.com/uploads/media/other/kaliuznii-d-2026-07-04-t-11-17-24.webp",
goals: "",
assists: "",
matches: "",
  },
  {
      name: "Рафаель Профіні",
      age: "22",
number: "6",
position: "Півзахисник",
nationality: "Аргентина",
photo: "https://fckharkiv.com/uploads/media/other/profini-d-2026-07-04-t-11-17-26.webp",
goals: "",
assists: "",
matches: "",
  },
  {
      name: "Олександр Яцик",
      age: "23",
number: "8",
position: "Півзахисник",
nationality: "Україна",
photo: "https://fckharkiv.com/uploads/media/other/iacik-d-2026-07-04-t-11-17-27.webp",
goals: "",
assists: "",
matches: "",
  },
  {
      name: "Денис Антюх",
      age: "28",
number: "9",
position: "Півзахисник",
nationality: "Україна",
photo: "https://fckharkiv.com/uploads/media/other/antiux-d-2026-07-04-t-11-17-22.webp",
goals: "",
assists: "",
matches: "",
  },
  {
      name: "Себастіан Кастільо",
      age: "21",
number: "11",
position: "Півзахисник",
nationality: "Венесуела",
photo: "https://fckharkiv.com/uploads/media/other/kastilyo-d-2026-07-04-t-11-17-24.webp",
goals: "",
assists: "",
matches: "",
  },
  {
      name: "Нікола Аревало",
      age: "23",
number: "16",
position: "Півзахисник",
nationality: "Колумбія",
photo: "https://fckharkiv.com/uploads/media/other/arevalo-d-2026-07-04-t-11-17-22.webp",
goals: "",
assists: "",
matches: "",
  },
  {
      name: "Рамік Гаджиєв",
      age: "20",
number: "14",
position: "Півзахисник",
nationality: "Україна",
photo: "https://fckharkiv.com/uploads/media/other/gadzijev-d-2026-07-04-t-11-17-22.webp",
goals: "",
assists: "",
matches: "",
  },
  {
      name: "Ігор Когут",
      age: "30",
number: "25",
position: "Півзахисник",
nationality: "Україна",
photo: "https://fckharkiv.com/uploads/media/other/kogut-d-2026-07-04-t-11-17-24.webp",
goals: "",
assists: "",
matches: "",
  },
{
      name: "Ермір Рашиця",
      age: "22",
number: "19",
position: "Півзахисник",
nationality: "Албанія",
photo: "https://fckharkiv.com/uploads/media/other/rasicia-d-2026-07-04-t-11-17-28.webp",
goals: "",
assists: "",
matches: "",
  },
  {
      name: "Кауан Баптістелла",
      age: "18",
number: "77",
position: "Півзахисник",
nationality: "Бразилія",
photo: "https://fckharkiv.com/uploads/media/other/baptistella-d-2026-07-04-t-11-17-22.webp",
goals: "",
assists: "",
matches: "",
  },
  {
      name: "Андрій Король",
      age: "18",
number: "88",
position: "Півзахисник",
nationality: "Україна",
photo: "https://fckharkiv.com/uploads/media/other/korol-d-2026-07-04-t-11-17-24.webp",
goals: "",
assists: "",
matches: "",
  },
  {
      name: "Матвій Панченко",
      age: "20",
number: "91",
position: "Півзахисник",
nationality: "Україна",
photo: "https://fckharkiv.com/uploads/media/other/pancenko-d-2026-07-04-t-11-17-25.webp",
goals: "",
assists: "",
matches: ""
  },
  {
      name: "Карлос Парако",
      age: "22",
number: "10",
position: "Нападник",
nationality: "Венесуела",
photo: "https://fckharkiv.com/uploads/media/other/parako-d-2026-07-04-t-11-17-25.webp",
goals: "",
assists: "",
matches: "",
  },
  {
      name: "Батон Забергджа",
      age: "25",
number: "26",
position: "Нападник",
nationality: "Косово",
photo: "https://fckharkiv.com/uploads/media/other/zabergdza-d-2026-07-04-t-11-17-23.webp",
goals: "",
assists: "",
matches: "",
  },
  {
      name: "Іван Багрій",
      age: "18",
number: "70",
position: "Нападник",
nationality: "Україна",
photo: "https://fckharkiv.com/uploads/media/other/bagrii-d-2026-07-04-t-11-17-22.webp",
goals: "",
assists: "",
matches: "",
  },
  {
      name: "Пітер Ітодо",
      age: "23",
number: "98",
position: "Нападник",
nationality: "Нігерія",
photo: "https://fckharkiv.com/uploads/media/other/itodo-01-d-2026-07-04-t-11-17-24.webp",
goals: "",
assists: "",
matches: "",
  },
  {
      name: "Крістіан Мба",
      age: "26",
number: "99",
position: "Нападник",
nationality: "Нігерія",
photo: "https://fckharkiv.com/uploads/media/other/mba-01-d-2026-07-04-t-11-17-25.webp",
goals: "",
assists: "",
matches: "",
  },
  
];
window.coaches = [
    {
    name: "Младен Бартулович",
    age: 39,
    position: "Тренерскій штаб",
    coach: "Головний Тренер",
    nationality: "Хорватія",
    photo: "https://fckharkiv.com/uploads/media/other/bartulovic-d-2026-07-04-t-11-17-23.webp",
  },
  {
    name: "Олександр Чижов",
    age: 39,
    position: "Тренерскій штаб",
    coach: "Асистент головного тренера",
    nationality: "Україна",
    photo: "https://fckharkiv.com/uploads/media/other/cizov-d-2026-07-10-t-12-41-19.webp",
  },
  {
    name: "Максим Цвиренко",
    age: 27,
    position: "Тренерскій штаб",
    coach: "Асистент головного тренера",
    nationality: "Україна",
    photo: "https://fckharkiv.com/uploads/media/other/cvirenko-d-2026-07-05-t-17-03-17.webp",
  },
  {
    name: "Євген Шахов",
    age: 35,
    position: "Тренерскій штаб",
    coach: "Асистент головного тренера",
    nationality: "Україна",
    photo: "https://fckharkiv.com/uploads/media/other/saxov-d-2026-07-10-t-12-40-41.webp",
  },
  {
    name: "Валентин Єрмак",
    age: 25,
    position: "Тренерскій штаб",
    coach: "Тренер аналітик",
    nationality: "Україна",
    photo: "https://fckharkiv.com/uploads/media/other/jermak-d-2026-07-04-t-11-17-27.webp",
  },
  {
    name: "Павло Таран",
    age: 37,
    position: "Тренерскій штаб",
    coach: "тренер аналітик",
    nationality: "Україна",
    photo: "https://fckharkiv.com/uploads/media/other/taran-d-2026-07-05-t-17-03-17.webp",
  },
  {
    name: "Сергій Долганьсикй",
    age: "51",
    position: "Тренерскій штаб",
    coach: "Тренер воротарфі",
    nationality: "Україна",
      photo: "https://fckharkiv.com/uploads/media/other/dolganskii-d-2026-07-04-t-11-17-23.webp",
  },
  {
    name: "Андрій Шабалін",
    age: "38",
    position: "Тренерскій штаб",
    coach: "Тренер з фізичної підготовки",
    nationality: "Україна",
      photo: "https://fckharkiv.com/uploads/media/other/sabalin-d-2026-07-05-t-17-03-17.webp",
  },
  {
    name: "Драган Тодорович",
    age: "38",
    position: "Тренерскій штаб",
    coach: "Тренер з фізичної підготовки",
    nationality: "Хорватія",
      photo: "https://fckharkiv.com/uploads/media/other/todorovic-d-2026-07-04-t-11-17-26.webp",
  },
];

window.managment = [
{
   name: "Богдан Бойко",
   role: "Президент",
   age: "27",
   nationality: "Україна",
   photo: "https://fckharkiv.com/uploads/content/managers/4/president-x-d-2026-06-14-t-16-25-04.png",
},
{
    name: "Володимир Носов",
    role: "Голова наглядової ради",
    age: "37",
    nationality: "Україна",
    photo: "https://fckharkiv.com/uploads/content/managers/5/nosov-x-d-2026-06-14-t-15-47-57.png",
},
{
    name: "Юрій Коротун",
    role: "Віцепрезидент",
    age: "41",
    nationality: "Україна",
    photo: "https://fckharkiv.com/uploads/content/managers/6/korotun-d-2026-07-10-t-00-41-03.webp",
},
{
    name: "Микола Павлов",
    role: "Радник президента з футболу",
    age: "72",
    nationality: "Україна",
    photo: "https://fckharkiv.com/uploads/settings/list/social/pavlov-01-d-2026-06-20-t-16-15-13.png",
},
{
    name: "Антон Іванов",
    role: "Генеральний директор",
    age: "43",
    nationality: "Україна",
    photo: "https://fckharkiv.com/uploads/content/managers/5/ivanov-x-d-2026-06-14-t-15-47-57.png",
},
{
    name: "Микола Шамардін",
    role: "Спортивний Директор",
    age: "42",
    nationality: "Україна",
    photo: "https://fckharkiv.com/uploads/content/managers/5/samardin-x-d-2026-06-14-t-15-47-57.png",
},


];
  window.matches = [
   {
       date: "1 серпня",
opponent: "Верес Рівне",
place: "Арена Лівій берег",
time: "15:30",
competition: "УПЛ",
   },
   {
       date: "8 серпня",
opponent: "Полісся Житомир",
place: "Стадіон Полісся",
time: "",
competition: "УПЛ",
   },
   {
       date: "15 серпня",
opponent: "Шахтар Донецьк",
place: "Арена Лівій Берег",
time: "",
competition: "УПЛ",
   },
   {
       date: "29 серпня",
opponent: "Зоря Луганськ",
place: "Стадіон Динамо імені Лобановського",
time: "",
competition: "УПЛ",
   },
   {
       date: "5 вересня",
opponent: "Оболонь Київ",
place: "Арена Лівій Берег",
time: "",
competition: "УПЛ",
   },
   {
       date: "12 вересня",
opponent: "Кривбас Кривий Ріг",
place: "Стадіон Гірник",
time: "",
competition: "УПЛ",
   },

];
window.results = [

];
